Feature/cha 56 candidates per place
tmek1244/IO-Project pull request #36
Opened 2021-05-08 17:06 UTC by sswrk

Endpoint zwracający liczbę kandydatów na miejsce dla danego kierunku w danym roku na danym stopniu

Ścieżka: **/api/backend/fields-of-study-candidates-per-place/**
Metoda HTTP: **POST**

Body requestu stanowią filtry. Poza _year_ wszystkie filtry są opcjonalne

```json
{
    "year":2019,
    "degree":7,
    "faculty":"WIET",
    "field_of_study":"Informatyka"
}
```

Zwracana jest tablica pasujących obiektów:

```json
{
        "name": "Informatyka",
        "faculty": "WIET",
        "degree": "7",
        "year": 2019,
        "candidates_per_place": 0.005
    }
```

2021-05-08 19:34 UTC, jnowakow commented
Patryk powiedz, czy pasuje Ci taki format

2021-05-08 20:55 UTC, tmek1244 commented on backend/views.py
> +            filters['faculty'] = faculty
Chyba wywali błąd jak nie będzie takiego kierunku (może jakiś try catch?)

2021-05-08 20:55 UTC, tmek1244 approved these changes

2021-05-08 23:27 UTC, skupien approved these changes
Ok!

2021-05-08 23:30 UTC, skupien requested changes
A jednak nie ok - mamy dostęp do tego endpointa bez podania Auth Key.
Oprócz tego wszystko gitówa.

2021-05-09 00:16 UTC, sswrk commented
> A jednak nie ok - mamy dostęp do tego endpointa bez podania Auth Key.
> Oprócz tego wszystko gitówa.

Ups 😶Pomyliłem się z dziedziczeniem tam, już poprawione

2021-05-09 00:26 UTC, merged