CHA-117 added field of study info to enpoints
tmek1244/IO-Project pull request #72
Opened 2021-05-31 13:14 UTC by sswrk

Typ studiów (stacjonarne/niestacjonarne) jest teraz obsługiwany na endpointach.

W przypadku zapytań metodą **POST**, filtr typu w body requestu: `"type": <typ>`
W odpowiedziach dodane zostało pole `"type": <typ>`

Plik .csv przesyłany pod endpoint **/upload/fields_of_study/{year}/** powinien być teraz w takim formacie: `degree,faculty,field_of_study,type,places,second_degree_field_of_study`

W przypadku zapytań metodą **GET**, zostały dodane/zmodyfikowane ścieżki:

/fields_of_studies/\<degree>/\<type>/
/field-conversion/\<int:year>/\<faculty>/\<field_of_study>/\<type>/
/status-distribution/\<int:year>/\<faculty>/\<degree>/\<type>/
/aam/\<degree>/\<faculty_year_list>)/\<type>/
/actual_recruitment_faculty_aggregation/faculty=\<faculty>&cycle=\<cycle>&type=\<type>
/fields-of-study-threshold/\<mode>/\<degree>/\<int:n>/\<int:year>/\<type>
/laureate_stats/\<int:n>/\<int:year>/\<str:type>
/faculty_popularity/\<str:pop_type>/\<str:degree>/\<int:n>/\<int:year>/\<str:type>/
/field-conversion-over-the-years/\<faculty>/\<field_of_study>/\<type>/
/points-distribution-over-the-years/\<int:step>/\<faculty>/\<type>/
/status-distribution-over-the-years/\<faculty>/\<field_of_study>/\<degree>/\<type>
/changes_after_cycle/\<faculty>/\<field_of_study>/\<degree>/\<year>/\<type>/
/last-rounds/\<faculty>/\<field_of_study>/\<degree>/\<type>

2021-05-31 20:20 UTC, jnowakow requested changes
Proszę o sprawdzenie tego o czym napisałem i ewentualne poprawki

2021-05-31 20:20 UTC, jnowakow commented on backend/urls.py
> +    path('field-conversion/<int:year>/<faculty>/<field_of_study>/<type>/',
Musi być także endpoint, który przyjmuje trzy argumenty rok, wydział, typ. Teraz jest tak, że trzeci argument jest traktowany jako kierunek i nie zwraca się nic.

2021-05-31 20:20 UTC, jnowakow commented on backend/urls.py
>          r'actual_recruitment_faculty_threshold/faculty=<faculty>'
brak dostosowania tego endpointa

2021-05-31 20:20 UTC, jnowakow commented on backend/urls.py
> +    re_path(r'^aam/(?P<degree>.+)/(?P<faculty_year_list>.+)/(?P<type>.+)/$',
Jeśli przykładowym wywołaniem jest /api/backend/aam/1/WIEiT+2020/stacjonarne to pojawia się kod 400.

2021-05-31 20:20 UTC, jnowakow commented on backend/urls.py
> +        r'^actual_recruitment_faculty_aggregation/faculty=(?P<faculty>.+)'
Na request http://localhost:3001/api/backend/actual_recruitment_faculty_aggregation/faculty=WIEiT&cycle=1&type=stacjonarne zwracana jest pusta lista.

2021-05-31 20:20 UTC, jnowakow commented on backend/views.py
> +    def get(self, request: Request, degree: str, type: str,
W jaki sposób przekazać do tego endpointa stopeń? Nie ma endpointa /threshold/<degree>/<type>/string, a po przekazaniu w stringu pojawi się błąd rozpakowania w lini `faculty, field = string.split('+')`

2021-05-31 20:20 UTC, jnowakow commented on backend/urls.py
> +    path('points-distribution-over-the-years/<int:step>/<faculty>/<type>/',
brak /backend/points-distribution-over-the-years/{step}/{faculty}/{field_of_study}/{degree}/{type}

2021-05-31 20:20 UTC, jnowakow commented on backend/urls.py
>      path('laureates-on-fofs/<faculty>/',
Brakuje też informacji o trybie w tym endpointcie

2021-05-31 21:28 UTC, sswrk commented on backend/urls.py
> +    path('field-conversion/<int:year>/<faculty>/<field_of_study>/<type>/',
Poprawione, dodałem taki endpoint: **/field-conversion/\<faculty>/\<type>/\<int:year>/**

2021-05-31 21:29 UTC, sswrk commented on backend/urls.py
>          r'actual_recruitment_faculty_threshold/faculty=<faculty>'
Naprawione

2021-05-31 21:29 UTC, sswrk commented on backend/urls.py
> +    re_path(r'^aam/(?P<degree>.+)/(?P<faculty_year_list>.+)/(?P<type>.+)/$',
Naprawione

2021-05-31 21:29 UTC, sswrk commented on backend/urls.py
> +        r'^actual_recruitment_faculty_aggregation/faculty=(?P<faculty>.+)'
Naprawione

2021-05-31 21:29 UTC, sswrk commented on backend/views.py
> +    def get(self, request: Request, degree: str, type: str,
Ścieżka: **/threshold/\<degree>/\<type>/\<string>/**

Np. /threshold/2/stacjonarne/WIET+Informatyka/

2021-05-31 21:29 UTC, sswrk commented on backend/urls.py
> +    path('points-distribution-over-the-years/<int:step>/<faculty>/<type>/',
Dodany

2021-05-31 21:29 UTC, sswrk commented on backend/urls.py
>      path('laureates-on-fofs/<faculty>/',
Jak powinna wyglądać odpowiedź?

2021-06-02 11:18 UTC, jnowakow requested changes

2021-06-02 11:18 UTC, jnowakow commented on backend/urls.py
>          r'actual_recruitment_faculty_threshold/faculty=<faculty>'
Tutaj też zwracana jest pusta lista bo brak  endpointa actual_recruitment_faculty_threshold/faculty=&cycle=&type=

2021-06-02 15:38 UTC, sswrk commented on backend/urls.py
>          r'actual_recruitment_faculty_threshold/faculty=<faculty>'
Endpoint dodany

2021-06-03 08:49 UTC, merged